@startuml
package "Underlying ML library" as ML {
  interface Predictor<R>
  interface DataFrame

  interface Classifier<R>
  interface Regressor<R>

  Predictor <|-- Classifier
  Predictor <|-- Regressor
}

package "Underlying Symbolic AI library" as AI {
  interface Rule
  interface Theory

  Theory " " *-right- "*" Rule
}

package Psyke {
  interface Extractor<R, P : Predictor<T>> {
    + predictor: P
    + discretization: Discretization
    + extract(DataFrame): Theory
    + predict(DataFrame): R
  }
}

Extractor "1" *-- "1" Predictor: wraps

DataFrame -left-> Extractor: input of
Extractor --> Theory: output of
@enduml